import { CardShape } from "./types";

//prettier-ignore
export const cards: CardShape[] = [
    { src: "/circles/blue_card_with_1_circles.png", shape: "circle", color: "blue", quantity: 1 },
    { src: "/circles/blue_card_with_2_circles.png", shape: "circle", color: "blue", quantity: 2 },
    { src: "/circles/blue_card_with_3_circles.png", shape: "circle", color: "blue", quantity: 3 },
    { src: "/circles/blue_card_with_4_circles.png", shape: "circle", color: "blue", quantity: 4 },
    { src: "/circles/green_card_with_1_circles.png", shape: "circle", color: "green", quantity: 1 },
    { src: "/circles/green_card_with_2_circles.png", shape: "circle", color: "green", quantity: 2 },
    { src: "/circles/green_card_with_3_circles.png", shape: "circle", color: "green", quantity: 3 },
    { src: "/circles/green_card_with_4_circles.png", shape: "circle", color: "green", quantity: 4 },
    { src: "/circles/red_card_with_1_circles.png", shape: "circle", color: "red", quantity: 1 },
    { src: "/circles/red_card_with_2_circles.png", shape: "circle", color: "red", quantity: 2 },
    { src: "/circles/red_card_with_3_circles.png", shape: "circle", color: "red", quantity: 3 },
    { src: "/circles/red_card_with_4_circles.png", shape: "circle", color: "red", quantity: 4 },
    { src: "/circles/yellow_card_with_1_circles.png", shape: "circle", color: "yellow", quantity: 1 },
    { src: "/circles/yellow_card_with_2_circles.png", shape: "circle", color: "yellow", quantity: 2 },
    { src: "/circles/yellow_card_with_3_circles.png", shape: "circle", color: "yellow", quantity: 3 },
    { src: "/circles/yellow_card_with_4_circles.png", shape: "circle", color: "yellow", quantity: 4 },

    { src: "/crosses/blue_card_with_1_crosses.png", shape: "cross", color: "blue", quantity: 1 },
    { src: "/crosses/blue_card_with_2_crosses.png", shape: "cross", color: "blue", quantity: 2 },
    { src: "/crosses/blue_card_with_3_crosses.png", shape: "cross", color: "blue", quantity: 3 },
    { src: "/crosses/blue_card_with_4_crosses.png", shape: "cross", color: "blue", quantity: 4 },
    { src: "/crosses/green_card_with_1_crosses.png", shape: "cross", color: "green", quantity: 1 },
    { src: "/crosses/green_card_with_2_crosses.png", shape: "cross", color: "green", quantity: 2 },
    { src: "/crosses/green_card_with_3_crosses.png", shape: "cross", color: "green", quantity: 3 },
    { src: "/crosses/green_card_with_4_crosses.png", shape: "cross", color: "green", quantity: 4 },
    { src: "/crosses/red_card_with_1_crosses.png", shape: "cross", color: "red", quantity: 1 },
    { src: "/crosses/red_card_with_2_crosses.png", shape: "cross", color: "red", quantity: 2 },
    { src: "/crosses/red_card_with_3_crosses.png", shape: "cross", color: "red", quantity: 3 },
    { src: "/crosses/red_card_with_4_crosses.png", shape: "cross", color: "red", quantity: 4 },
    { src: "/crosses/yellow_card_with_1_crosses.png", shape: "cross", color: "yellow", quantity: 1 },
    { src: "/crosses/yellow_card_with_2_crosses.png", shape: "cross", color: "yellow", quantity: 2 },
    { src: "/crosses/yellow_card_with_3_crosses.png", shape: "cross", color: "yellow", quantity: 3 },
    { src: "/crosses/yellow_card_with_4_crosses.png", shape: "cross", color: "yellow", quantity: 4 },

    { src: "/stars/blue_card_with_1_stars.png", shape: "star", color: "blue", quantity: 1 },
    { src: "/stars/blue_card_with_2_stars.png", shape: "star", color: "blue", quantity: 2 },
    { src: "/stars/blue_card_with_3_stars.png", shape: "star", color: "blue", quantity: 3 },
    { src: "/stars/blue_card_with_4_stars.png", shape: "star", color: "blue", quantity: 4 },
    { src: "/stars/green_card_with_1_stars.png", shape: "star", color: "green", quantity: 1 },
    { src: "/stars/green_card_with_2_stars.png", shape: "star", color: "green", quantity: 2 },
    { src: "/stars/green_card_with_3_stars.png", shape: "star", color: "green", quantity: 3 },
    { src: "/stars/green_card_with_4_stars.png", shape: "star", color: "green", quantity: 4 },
    { src: "/stars/red_card_with_1_stars.png", shape: "star", color: "red", quantity: 1 },
    { src: "/stars/red_card_with_2_stars.png", shape: "star", color: "red", quantity: 2 },
    { src: "/stars/red_card_with_3_stars.png", shape: "star", color: "red", quantity: 3 },
    { src: "/stars/red_card_with_4_stars.png", shape: "star", color: "red", quantity: 4 },
    { src: "/stars/yellow_card_with_1_stars.png", shape: "star", color: "yellow", quantity: 1 },
    { src: "/stars/yellow_card_with_2_stars.png", shape: "star", color: "yellow", quantity: 2 },
    { src: "/stars/yellow_card_with_3_stars.png", shape: "star", color: "yellow", quantity: 3 },
    { src: "/stars/yellow_card_with_4_stars.png", shape: "star", color: "yellow", quantity: 4 },
    
    { src: "/triangles/blue_card_with_1_triangles.png", shape: "triangle", color: "blue", quantity: 1 },
    { src: "/triangles/blue_card_with_2_triangles.png", shape: "triangle", color: "blue", quantity: 2 },
    { src: "/triangles/blue_card_with_3_triangles.png", shape: "triangle", color: "blue", quantity: 3 },
    { src: "/triangles/blue_card_with_4_triangles.png", shape: "triangle", color: "blue", quantity: 4 },
    { src: "/triangles/green_card_with_1_triangles.png", shape: "triangle", color: "green", quantity: 1 },
    { src: "/triangles/green_card_with_2_triangles.png", shape: "triangle", color: "green", quantity: 2 },
    { src: "/triangles/green_card_with_4_triangles.png", shape: "triangle", color: "green", quantity: 3 },
    { src: "/triangles/green_card_with_4_triangles.png", shape: "triangle", color: "green", quantity: 4 },
    { src: "/triangles/red_card_with_1_triangles.png", shape: "triangle", color: "red", quantity: 1 },
    { src: "/triangles/red_card_with_2_triangles.png", shape: "triangle", color: "red", quantity: 2 },
    { src: "/triangles/red_card_with_3_triangles.png", shape: "triangle", color: "red", quantity: 3 },
    { src: "/triangles/red_card_with_4_triangles.png", shape: "triangle", color: "red", quantity: 4 },
    { src: "/triangles/yellow_card_with_1_triangles.png", shape: "triangle", color: "yellow", quantity: 1 },
    { src: "/triangles/yellow_card_with_2_triangles.png", shape: "triangle", color: "yellow", quantity: 2 },
    { src: "/triangles/yellow_card_with_3_triangles.png", shape: "triangle", color: "yellow", quantity: 3 },
    { src: "/triangles/yellow_card_with_4_triangles.png", shape: "triangle", color: "yellow", quantity: 4 },
]

//prettier-ignore
export const initialCards: CardShape[] = [
    { src: "/circles/red_card_with_1_circles.png", shape: "circle", color: "red", quantity: 1 },
    { src: "/triangles/green_card_with_2_triangles.png", shape: "triangle", color: "green", quantity: 2 },
    { src: "/crosses/blue_card_with_3_crosses.png", shape: "cross", color: "blue", quantity: 3 },
    { src: "/stars/yellow_card_with_4_stars.png", shape: "star", color: "yellow", quantity: 4 },
]
